services:
  bbf:
    container_name: babelfishpg
    image: ghcr.io/plataform3/babelfish-on-docker:latest
    ports:
      # Port forwarding not supported by BabelfishPG
      - 1433:1433
      - 15432:5432
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - BABELFISH_USER=bbf
      - BABELFISH_PASS=password
      - BABELFISH_DB=bbf
      - BABELFISH_MIGRATION_MODE=multi-db
      - POSTGRES_HOST_AUTH_METHOD=trust
    command: >
      postgres -c babelfishpg_tsql.trace_exec_time="on"
               -c babelfishpg_tsql.trace_exec_codes="on" 
               -c babelfishpg_tsql.trace_exec_counts="on" 
               -c babelfishpg_tds.tds_debug_log_level="2"
               -c babelfishpg_tsql.explain_timing="on"
               -c babelfishpg_tsql.explain_summary="on"
               -c babelfishpg_tsql.showplan_text="on"
               -c babelfishpg_tsql.enable_tsql_information_schema="on"
               -c babelfishpg_tds.listen_addresses="*"
               -c logging_collector="on"
               -c log_min_duration_statement=1000
               -c listen_addresses="*"
    networks:
      - babelfish
    volumes:
      - bbfdata:/var/lib/postgresql/data
      # - ./docker/bbf:/docker-entrypoint-initdb.d
  
  ## WIP
  # tsql:
  #   container_name: tsql
  #   build:
  #     context: ./docker/tsql/
  #     dockerfile: Dockerfile
  #   depends_on:
  #     - bbf
  #   command: >
  #     sleep 10 && /usr/bin/001_init.sh 
  #   networks:
  #     - babelfish
  #   volumes:
  #     - ./docker/bbf/001_init.sh:/usr/bin/001_init.sh

volumes:
  bbfdata:
    driver: local

networks:
  babelfish:
